from __future__ import annotations

from collections import defaultdict

from app.schemas import ProblemItem, StructuredRecord, TimelineEvent


def build_timeline_and_problems(record: StructuredRecord) -> None:
    """Derived views are conservative: chronology uses only explicit source dates."""
    events: list[TimelineEvent] = []
    by_date: dict[str, list] = defaultdict(list)
    for lab in record.laboratory_results:
        if lab.date:
            by_date[lab.date].append(lab)
    for event_date, labs in by_date.items():
        summary = "; ".join(lab.value_text or f"{lab.test_name_original}: {lab.value}" for lab in labs)
        events.append(TimelineEvent(date=event_date, event="Laboratory results", summary=summary, source_refs=[lab.source_ref for lab in labs]))
    if record.ai_clinical_review and record.timeline:
        # Patient-level AI already reviewed all encounters and preserves the
        # longitudinal chronology.  Add any typed lab events only when they
        # are not already represented in that canonical timeline.
        existing_keys = {(item.date, item.event, item.summary) for item in record.timeline}
        record.timeline.extend(event for event in events if (event.date, event.event, event.summary) not in existing_keys)
        record.timeline = sorted(record.timeline, key=lambda event: event.date or "9999-12-31")
    else:
        record.timeline = sorted(events, key=lambda event: event.date or "9999-12-31")

    existing = {(item.problem.lower(), item.source_type) for item in record.problem_list}
    for diagnosis in record.diagnoses:
        if diagnosis.type == "documented" and (diagnosis.term_original.lower(), "documented") not in existing:
            record.problem_list.append(ProblemItem(
                problem=diagnosis.term_original, status=diagnosis.status,
                source_type="documented", source_refs=[diagnosis.source_ref],
            ))
            existing.add((diagnosis.term_original.lower(), "documented"))


def physician_summary(record: StructuredRecord) -> str:
    """Plain clinical English, capped to a concise one-page style output."""
    lines = ["Patient Identification", f"Patient ID: {record.patient.patient_id}", ""]
    lines.append("Clinical Summary")
    documented = [item.term_original for item in record.diagnoses if item.type == "documented"]
    if documented:
        lines.append("Documented diagnoses: " + "; ".join(documented) + ".")
    else:
        lines.append("No clearly documented diagnosis was extracted from the available machine-readable source text.")
    lines.extend(["", "Key Investigations"])
    if record.laboratory_results:
        grouped = "; ".join(item.value_text or f"{item.test_name_original}: {item.value}" for item in record.laboratory_results[:12])
        lines.append(grouped + ".")
    else:
        lines.append("No structured laboratory values extracted.")
    lines.extend(["", "Medication History"])
    if record.medications:
        lines.append("; ".join((item.name_original or "Unidentified medication") for item in record.medications) + ". Details require reconciliation before ERP entry.")
    else:
        lines.append("No structured medication entries extracted.")
    lines.extend(["", "Growth / Vitals"])
    if record.growth_measurements:
        lines.append("Numeric growth measurements extracted; exact percentile assessment is not generated by this MVP.")
    else:
        lines.append("No structured growth or vital-sign measurements extracted.")
    lines.extend(["", "Allergy Status", "No allergy status was extracted; this is not evidence of no allergy.", "", "Active Problems"])
    lines.append("; ".join(item.problem for item in record.problem_list) if record.problem_list else "No active problem list generated from documented diagnoses.")
    lines.extend(["", "Recommended Follow-up / Items Requiring Verification"])
    if record.verification_queue:
        lines.append(f"{len(record.verification_queue)} item(s) require human review before clinical or ERP use.")
        for item in record.verification_queue[:8]:
            lines.append(f"- {item.field}: {item.reason} (source {item.source_ref.source_file}, page {item.source_ref.source_page})")
    else:
        lines.append("No items are currently queued; routine clinical validation remains required.")
    return "\n".join(lines)[:5000]
