"""initial medical mvp schema

Revision ID: 38239527d854
Revises: 
Create Date: 2026-09-10 00:07:23.887994
"""
from alembic import op
import sqlalchemy as sa

revision = '38239527d854'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('patient_id', sa.String(length=128), nullable=False),
    sa.Column('hospital_file_number', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('audit_events',
    sa.Column('fact_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=128), nullable=False),
    sa.Column('field', sa.String(length=255), nullable=False),
    sa.Column('source_file', sa.String(length=512), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('fact_id')
    )
    op.create_index(op.f('ix_audit_events_patient_id'), 'audit_events', ['patient_id'], unique=False)
    op.create_table('clinical_interpretations',
    sa.Column('interpretation_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=128), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=False),
    sa.Column('certainty', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('interpretation_id')
    )
    op.create_index(op.f('ix_clinical_interpretations_patient_id'), 'clinical_interpretations', ['patient_id'], unique=False)
    op.create_table('diagnoses',
    sa.Column('diagnosis_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=128), nullable=False),
    sa.Column('term_original', sa.String(length=512), nullable=False),
    sa.Column('certainty', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('diagnosis_id')
    )
    op.create_index(op.f('ix_diagnoses_patient_id'), 'diagnoses', ['patient_id'], unique=False)
    op.create_table('encounters',
    sa.Column('encounter_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=128), nullable=False),
    sa.Column('encounter_date', sa.String(length=32), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('encounter_id')
    )
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    op.create_table('growth_measurements',
    sa.Column('measurement_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=128), nullable=False),
    sa.Column('measurement_date', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('measurement_id')
    )
    op.create_index(op.f('ix_growth_measurements_patient_id'), 'growth_measurements', ['patient_id'], unique=False)
    op.create_table('laboratory_results',
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=128), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index(op.f('ix_laboratory_results_patient_id'), 'laboratory_results', ['patient_id'], unique=False)
    op.create_table('medications',
    sa.Column('medication_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=128), nullable=False),
    sa.Column('name_normalized', sa.String(length=512), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('medication_id')
    )
    op.create_index(op.f('ix_medications_patient_id'), 'medications', ['patient_id'], unique=False)
    op.create_table('observations',
    sa.Column('observation_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('observation_id')
    )
    op.create_index(op.f('ix_observations_patient_id'), 'observations', ['patient_id'], unique=False)
    op.create_table('patient_records',
    sa.Column('patient_id', sa.String(length=128), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('processing_status', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('problem_list',
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=128), nullable=False),
    sa.Column('problem', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('problem_id')
    )
    op.create_index(op.f('ix_problem_list_patient_id'), 'problem_list', ['patient_id'], unique=False)
    op.create_table('radiology_reports',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=128), nullable=False),
    sa.Column('study_type', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_radiology_reports_patient_id'), 'radiology_reports', ['patient_id'], unique=False)
    op.create_table('source_files',
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=128), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('processing_status', sa.String(length=64), nullable=False),
    sa.Column('original_path', sa.Text(), nullable=False),
    sa.Column('processed_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('checksum', name='uq_source_file_checksum')
    )
    op.create_index(op.f('ix_source_files_patient_id'), 'source_files', ['patient_id'], unique=False)
    op.create_table('verification_items',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=128), nullable=False),
    sa.Column('field', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_verification_items_patient_id'), 'verification_items', ['patient_id'], unique=False)
    op.create_table('source_pages',
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=False),
    sa.Column('extraction_status', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['source_files.file_id'], ),
    sa.PrimaryKeyConstraint('page_id')
    )
    op.create_index(op.f('ix_source_pages_file_id'), 'source_pages', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_pages_file_id'), table_name='source_pages')
    op.drop_table('source_pages')
    op.drop_index(op.f('ix_verification_items_patient_id'), table_name='verification_items')
    op.drop_table('verification_items')
    op.drop_index(op.f('ix_source_files_patient_id'), table_name='source_files')
    op.drop_table('source_files')
    op.drop_index(op.f('ix_radiology_reports_patient_id'), table_name='radiology_reports')
    op.drop_table('radiology_reports')
    op.drop_index(op.f('ix_problem_list_patient_id'), table_name='problem_list')
    op.drop_table('problem_list')
    op.drop_table('patient_records')
    op.drop_index(op.f('ix_observations_patient_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_medications_patient_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_laboratory_results_patient_id'), table_name='laboratory_results')
    op.drop_table('laboratory_results')
    op.drop_index(op.f('ix_growth_measurements_patient_id'), table_name='growth_measurements')
    op.drop_table('growth_measurements')
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_diagnoses_patient_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_clinical_interpretations_patient_id'), table_name='clinical_interpretations')
    op.drop_table('clinical_interpretations')
    op.drop_index(op.f('ix_audit_events_patient_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('patients')
    # ### end Alembic commands ###
