"""patient workspace reports and jobs

Revision ID: 8a60bdf38177
Revises: 38239527d854
Create Date: 2026-09-10 01:37:49.616847
"""
from alembic import op
import sqlalchemy as sa

revision = '8a60bdf38177'
down_revision = '38239527d854'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_generation_jobs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=128), nullable=False),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_report_generation_jobs_patient_id'), 'report_generation_jobs', ['patient_id'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=128), nullable=False),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('text_path', sa.Text(), nullable=True),
    sa.Column('json_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('source_record_hash', sa.String(length=64), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('patient_id', 'report_type', 'version', name='uq_report_patient_type_version')
    )
    op.create_index(op.f('ix_reports_patient_id'), 'reports', ['patient_id'], unique=False)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_table('report_source_links',
    sa.Column('link_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['source_files.file_id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.report_id'], ),
    sa.PrimaryKeyConstraint('link_id')
    )
    op.create_index(op.f('ix_report_source_links_file_id'), 'report_source_links', ['file_id'], unique=False)
    op.create_index(op.f('ix_report_source_links_report_id'), 'report_source_links', ['report_id'], unique=False)
    op.add_column('patients', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('sex', sa.String(length=64), nullable=True))
    op.add_column('patients', sa.Column('date_of_birth', sa.String(length=32), nullable=True))
    op.add_column('patients', sa.Column('nationality', sa.String(length=128), nullable=True))
    op.add_column('patients', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('last_processed_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('patients', sa.Column('processing_status', sa.String(length=64), server_default='pending', nullable=False))
    op.add_column('patients', sa.Column('review_status', sa.String(length=64), server_default='pending', nullable=False))
    op.create_index(op.f('ix_patients_full_name'), 'patients', ['full_name'], unique=False)
    op.add_column('source_files', sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_files', 'ingested_at')
    op.drop_index(op.f('ix_patients_full_name'), table_name='patients')
    op.drop_column('patients', 'review_status')
    op.drop_column('patients', 'processing_status')
    op.drop_column('patients', 'last_processed_at')
    op.drop_column('patients', 'address')
    op.drop_column('patients', 'nationality')
    op.drop_column('patients', 'date_of_birth')
    op.drop_column('patients', 'sex')
    op.drop_column('patients', 'full_name')
    op.drop_index(op.f('ix_report_source_links_report_id'), table_name='report_source_links')
    op.drop_index(op.f('ix_report_source_links_file_id'), table_name='report_source_links')
    op.drop_table('report_source_links')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_patient_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_report_generation_jobs_patient_id'), table_name='report_generation_jobs')
    op.drop_table('report_generation_jobs')
    # ### end Alembic commands ###
